DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY (
  name VARCHAR(250) UNIQUE NOT NULL,
  currency VARCHAR(3) NOT NULL,
  CONSTRAINT COUNTRY_PRIMARY_KEY PRIMARY KEY (name)
);

DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY (
  name VARCHAR(250) UNIQUE NOT NULL,
  country_name VARCHAR(250) NOT NULL,
  current_budget DECIMAL(20, 2) NOT NULL,
  allocated_budget DECIMAL(20, 2) NOT NULL,
  foundation_date DATE NOT NULL,
  CONSTRAINT COMPANY_PRIMARY_KEY PRIMARY KEY (name),
  CONSTRAINT COMPANY_FOREIGN_KEY FOREIGN KEY (country_name) REFERENCES COUNTRY (name)
);

DROP TABLE IF EXISTS BUDGET;
CREATE TABLE BUDGET (
  id INT AUTO_INCREMENT UNIQUE NOT NULL,
  start_date DATE NOT NULL,
  finish_date DATE NOT NULL,
  months_number INT NOT NULL,
  monthly_payment DECIMAL(20, 2) NOT NULL,
  total_payment DECIMAL(30, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  CONSTRAINT BUDGET_PRIMARY_KEY PRIMARY KEY (id)
);

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT (
  id INT AUTO_INCREMENT UNIQUE NOT NULL,
  name VARCHAR(250) UNIQUE NOT NULL,
  company_name VARCHAR(250) NOT NULL,
  staff_skill_level VARCHAR(2) NOT NULL,
  staff_number INT NOT NULL,
  budget_id INT NOT NULL,
  CONSTRAINT PROJECT_PRIMARY_KEY PRIMARY KEY (id),
  CONSTRAINT PROJECT_FOREIGN_KEY FOREIGN KEY (company_name) REFERENCES COMPANY (name),
  CONSTRAINT PROJECT_FOREIGN_KEY2 FOREIGN KEY (budget_id) REFERENCES BUDGET (id)
);

DROP TABLE IF EXISTS SKILL_PAYMENT;
CREATE TABLE SKILL_PAYMENT (
  id INT AUTO_INCREMENT UNIQUE NOT NULL,
  country_name VARCHAR(250) NOT NULL,
  skill_level VARCHAR(2) NOT NULL,
  monthly_payment DECIMAL(20, 2) NOT NULL,
  CONSTRAINT SKILL_PAYMENT_PRIMARY_KEY PRIMARY KEY (id),
  CONSTRAINT SKILL_PAYMENT_FOREIGN_KEY FOREIGN KEY (country_name) REFERENCES COUNTRY (name)
);